### ISSUE TITLE
无法编译

### ISSUE THREAD

**Issue by themass** [netease-kit/nim-uikit-android#116]
Plugin [id: 'com.android.application', version: '7.1.2', apply: false] was not found in any of the following sources:

**Comment by shine2008** [comment]
好的，我们试一下这个版本

**Comment by shine2008** [comment]
您好，我试了一下7.1.2没有问题。您试一下：下载工程在根目录修改build.gradle.kts文件，修改配置。能够正常运行。
        id("com.android.library") version "7.1.2" apply false
        id("com.android.application") version "7.1.2" apply false
        id("org.jetbrains.kotlin.android") version "1.9.0" apply false

**Comment by shine2008** [comment]
不知道您是在哪里配置的，应该是配置语法的问题
