### ISSUE TITLE
调用NimUIKit.init后doLogin收不到回调

### ISSUE THREAD

**Issue by mikiller** [netease-kit/nim-uikit-android#13]
如题，接入NimUIKit之前，可以正常登陆，接收RequestCallback回调。但是在Application中调用NimUIKit.init之后，便无法收到回调。可能是什么原因？

**Comment by winniexuwen** [comment]
报什么错误吗？

**Comment by mikiller** [comment]
已解决，初始化前未做主进程判断

**Comment by leejay001** [comment]
我是做了主进程判断，然而登录会失败，一直返回408错误

**Comment by xingstarx** [comment]
恩，同样碰到这个问题
