### ISSUE TITLE
集成最近会话fragment失败

### ISSUE THREAD

**Issue by jameschen4540** [netease-kit/nim-uikit-android#19]
无论通过静态集成还是动态集成，都无法集成

**Comment by 1136535305** [comment]
我能吐槽一下吗，静态集成最近会话fragment里Readme.MD文档里引用的包名是这样的：
  android:name="com.netease.nim.uikit.recent.RecentContactsFragment"

然后我死活找不到该类，然后我看了一下源码，最后换成了：  
 android:name="com.netease.nim.uikit.business.recent.RecentContactsFragment"

嚓。。。。。我很怀疑文档没有及时更新

**Comment by manburenshenglu** [comment]
吐槽+11111，官方文档里引用的包名是这样的：
android:name="com.netease.nim.uikit.recent.RecentContactsFragment"，，，，结果路径应该是android:name="com.netease.nim.uikit.business.recent.RecentContactsFragment"才对
