### ISSUE TITLE
毫无架构可言,只会堆代码的垃圾SDK

### ISSUE THREAD

**Issue by wqandroid** [netease-kit/nim-uikit-android#27]
你这sdk,小学生写的吗?

**Comment by wen704** [comment]
赞成,耦合度太高了,根本抽不出单独的

**Comment by captain-miao** [comment]
都怪自己眼瞎，选了这家。

**Comment by wqandroid** [comment]
看到那么多人抱怨.网易竟然毫无改进 .真是6的一批

**Comment by leejay001** [comment]
这代码写的真的是一言难尽

**Comment by Robin-Gao** [comment]
已经集成两天了......各种报错，冲突

**Comment by moo611** [comment]
开发者文档可真简洁，明明需要接入UIKit,开发文档里竟然没有写如何使用，还是从网上找到的各种资料

**Comment by septenaryf** [comment]
**不建议 阅读 本仓库的 代码，也没啥参考价值**

避免走弯路，建议直接看  [接口文档]( https://dev.yunxin.163.com/docs/product/IM即时通讯/SDK开发集成/) 吧

**Comment by moo611** [comment]
> **Ugly code，wasting your valuable time!!!**
> 
> 不建议阅读本仓库的代码，避免走弯路，建议直接看 [接口文档](https://dev.yunxin.163.com/docs/product/IM%E5%8D%B3%E6%97%B6%E9%80%9A%E8%AE%AF/SDK%E5%BC%80%E5%8F%91%E9%9B%86%E6%88%90/) 吧

我说的就是文档啊，文档根本没写怎么接UIKIT

**Comment by glassesmonkey** [comment]
UIKIT只是示例吧，又不是非要接UIKIT才能用的

**Comment by Routee** [comment]
真是💩一样的sdk

**Comment by DevXue** [comment]
2017年的时候准备接入聊天功能，那会看了下这个SDK，  写的真是TMD一坨狗屎，现在还是这个鸟样子··  我TM醉了。。

**Comment by NicalDai** [comment]
UIKit导入项目的时候遇到问题，可以看下这个demo https://github.com/netease-im/NIM_Android_Demo/tree/master/demo

**Comment by skyliwq** [comment]
网易云信代码确实垃圾

**Comment by liu19890210** [comment]
@NicalDai 群列表要设置某个群置顶？

**Comment by mrme2014** [comment]
要不让外包来写把
