### ISSUE TITLE
可考虑发布在Maven 或 Jcenter 每一会更新都很麻烦。

### ISSUE THREAD

**Issue by luluneverdie** [netease-kit/nim-uikit-android#28]
可以建议用户与其改在 UIkit 的 module 里， 可以建议用户 extend UIkit 包里的Class。长期下去会成为升级的噩梦。

**Comment by NicalDai** [comment]
UIKit只是一个参考哈，大部分开发者基于UIKit的源码做了很多深度的定制，这个比较合适的方式是开发者自己改成自己的一套UI，后续自行维护。sdk会升级，但是UIKit一般安卓那边没有大改，是不会做调整的
