### ISSUE TITLE
愿意接受字串翻译的代码吗？

### ISSUE THREAD

**Issue by cchitsiang** [netease-kit/nim-uikit-android#31]
![image](https://user-images.githubusercontent.com/343107/42105966-e3d38102-7c04-11e8-8bde-3e24616c9975.png)
你可以参考图片上的代码，整个SDK很多地方直接用上了中文的string，比较恰当的方式应该全部都放到strings.xml的文件上的，指的是R.string

就算没有打算维护其他语言的翻译，但是如果全部都在strings.xml的话，对于用这个SDK并支持其它语言的APP，也相对容易维护

**Comment by NicalDai** [comment]
嗯嗯，uikit也是不停在优化的，这块都是开源的哈，开发者可以自行调整。sdk层面没有文案的配置的，这块是uikit的逻辑
