### ISSUE TITLE
RecentContactsFragment最近聊天列表。不能显示用户头像怎么回事

### ISSUE THREAD

**Issue by AlexanderLee111** [netease-kit/nim-uikit-android#32]
我在集成UIKit之后，把RecentContactsFragment集成到自己的界面之后，联系人列表不显示头像。但是我debug进去之后，联系人头像url是有的。
我集成的界面：
![image](https://user-images.githubusercontent.com/29690512/42822048-9ecb5d94-8a0c-11e8-8a30-327043e64d26.png)

debug时的数据：
<img width="1378" alt="image" src="https://user-images.githubusercontent.com/29690512/42821905-38442312-8a0c-11e8-953e-973f6b78803f.png">

**Comment by NicalDai** [comment]
完整的url看看，是不是有加了个缩略图的后缀

**Comment by AlexanderLee111** [comment]
已解决，因为后台url并不完整，缺少http前缀，麻烦您了

获取 Outlook for iOS<https://aka.ms/o0ukef>

________________________________
收件人: NicalDai <notifications@github.com>
发送时间: 星期四, 十一月 22, 2018 11:14 上午
收件人: netease-im/NIM_Android_UIKit
抄送: AlexanderLee; Author
主题: Re: [netease-im/NIM_Android_UIKit] RecentContactsFragment最近聊天列表。不能显示用户头像怎么回事 (#32)


完整的url看看，是不是有加了个缩略图的后缀

―
