### ISSUE TITLE
Program type already present: com.netease.nimlib.avchat.a.a.a.d

### ISSUE THREAD

**Issue by richfuns** [netease-kit/nim-uikit-android#34]
在空白项目导入uikit module后，报错啊
Program type already present: com.netease.nimlib.avchat.a.a.a.d
Message{kind=ERROR, text=Program type already present: com.netease.nimlib.avchat.a.a.a.d, sources=[Unknown source file], tool name=Optional.of(D8)}

gradle 4.4
插件： 3.1.3

请教这是什么原因？谢谢

**Comment by richfuns** [comment]
Program type already present: com.netease.nimlib.avchat.AVChatService
Message{kind=ERROR, text=Program type already present: com.netease.nimlib.avchat.AVChatService, sources=[Unknown source file], tool name=Optional.of(D8)}

**Comment by NicalDai** [comment]
依赖冲突了，看看AVChat的jar是不是重复依赖了

**Comment by sunlinkun** [comment]
看看是不是gradle与libs里导包是不是重复了
