### ISSUE TITLE
不支持  androidx support library 是吗

### ISSUE THREAD

**Issue by gitxiaojin** [netease-kit/nim-uikit-android#44]
不支持  androidx support library 是吗

**Comment by NicalDai** [comment]
暂时没单独做过适配

**Comment by zs1973** [comment]
> 不支持 androidx support library 是吗

咋弄的 兄弟  最后自己适配的吗？

**Comment by septenaryf** [comment]
AS [migerate to androidx] 稍微调整下 就可以的

**Comment by zs1973** [comment]
> AS [migrate to androidx] 稍微调整下 就可以的

话说都是对接的uikit吗 复杂的需求  uikit可以实现吗 我现在一头雾水  不晓得该从哪下手
