### ISSUE TITLE
集成最近联系人

### ISSUE THREAD

**Issue by zzwei114** [netease-kit/nim-uikit-android#47]
集成的最近联系人 ， 如果app进程被意外杀死 ， 自动登录之后离线的消息刷新不出来，手动登录之后离线消息会刷新出来。
 NIMClient.getService(MsgService.class).queryRecentContacts().setCallback(new RequestCallbackWrapper<List<RecentContact>>() {

                    @Override
                    public void onResult(int code, List<RecentContact> recents, Throwable exception) {
                        if (code != ResponseCode.RES_SUCCESS || recents == null) {
                            return;
                        }
                        loadedRecents = recents;
recents里边并没有离线的消息，是需要开发者自己手动添加进去吗？

**Comment by yanchengdeng** [comment]
华为手机 进程杀掉后   偶先 只能获取到accid 对应的用户名获取不到！

**Comment by NicalDai** [comment]
名片要单独查的，这里只有一个accid
