### ISSUE TITLE
集成UIKit后无法使用初始化

### ISSUE THREAD

**Issue by rmtic** [netease-kit/nim-uikit-android#52]

**Comment by glassesmonkey** [comment]
有具体报错吗

**Comment by cjc147** [comment]
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/netease/nimlib/i/j;

**Comment by FreeSunny** [comment]
> java.lang.NoClassDefFoundError: Failed resolution of: Lcom/netease/nimlib/i/j;

应该混淆的问题

**Comment by gufengpiaoyi** [comment]
同样的问题，java.lang.NoClassDefFoundError: Failed resolution of: Lcom/netease/nimlib/i/j;，debug没开混淆。不集成该uikit可以初始化

**Comment by shine2008** [comment]
UIKit的版本是多少？采用什么样的集成方式？UI层源码依赖还是AAR依赖？

**Comment by shine2008** [comment]
> 同样的问题，java.lang.NoClassDefFoundError: Failed resolution of: Lcom/netease/nimlib/i/j;，debug没开混淆。不集成该uikit可以初始化

UIKit的版本是多少？采用什么样的集成方式？UI层源码依赖还是AAR依赖？

**Comment by rmtic** [comment]
你好，您发送的邮件我已经收到！ 
#mailContentContainer .txt {height:auto;}
