### ISSUE TITLE
IM 推送问题

### ISSUE THREAD

**Issue by wuhui0930** [netease-kit/nim-uikit-android#53]
已引入 nim-push-7.0.1.jar

vivo手机报错： Caused by: java.lang.ClassNotFoundException: Didn't find class "com.vivo.push.PushClient" on path: DexPathList[[zip file "/system/framework/com.android.support.jar", zip file "/data/app/com.项目.包名-08MB_Zs_MUKqSf0fIM3PxQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.项目.包名-08MB_Zs_MUKqSf0fIM3PxQ==/lib/arm64, /data/app/com.项目.包名-08MB_Zs_MUKqSf0fIM3PxQ==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]

其余品牌测试机目前无问题。

尚不知问题出在哪里，还望指点。

**Comment by NicalDai** [comment]
oppo推送的sdk得导入一下，看下demo吧，或者升级一下sdk版本
