### ISSUE TITLE
聊天界面发送图片失败

### ISSUE THREAD

**Issue by xingjianlong** [netease-kit/nim-uikit-android#57]
发送图片时候一直显示红色叹号，返回403错误
抓到发送图片返回结果
{"requestId":"32bbf89b2d7f000000005ed73e518018","errCode":"AccessDenied","errMsg":"ErrMsg : AccessNotExist, ErrDesc : error_accesskey_not_exist, Resource : %2Fyunxin%2FMTAwMDAwNA%3D%3D%2FbmltYV8xMzAzNjcyMjY1XzE1OTExNjI4NDE3OTBfOGU4NDRjMmUtY2ZhZC00ZTkwLTk3ZWItZDhmNDhiYjU0ZmM4, RequestId : 0118f2500a820000017278cb6da86323"}

**Comment by NicalDai** [comment]
这是怎么发的图片，哪个接口上传的？
