### ISSUE TITLE
集成最近联系人列表之后，没有收到消息

### ISSUE THREAD

**Issue by ling9400** [netease-kit/nim-uikit-android#58]
操作是这样的：两个设备一个登陆成功了之后调用私聊接口给另一个发消息，但另一个没有收到消息，是需要配置推送吗？还是说需要添加好友？或者说是需要其他什么配置么？

**Comment by NicalDai** [comment]
回调走了吗？observeReceiveMessage

**Comment by ichanghe** [comment]
是怎么解决的？可以分享一下吗
