### ISSUE TITLE
ConversationUIConfig Bug设置不生效

### ISSUE THREAD

**Issue by hhh88711** [netease-kit/nim-uikit-android#78]
## 修改ConversationUIConfig不生效
```java
// 修改这几个不生效,
  public boolean showTitleBarLeftIcon = false;
  public boolean showTitleBarRightIcon = false;
  public boolean showTitleBarRight2Icon = false;
```
## 代码逻辑问题?
```java
// conversationkit-ui/src/main/java/com/netease/yunxin/kit/conversationkit/ui/page/ConversationFragment.java
private void loadUIConfig(){
 // 这里看看
}
```

## 其他问题
```text
想实现撤回消息不显示："此消息已撤回"?要如何实现望告知🥺🥺🥺🥺🥺🥺
```

@shuine 
@shine2008

**Comment by shine2008** [comment]
在ChatMessageAdapter类中，下面是撤回逻辑的代码
    public void revokeMessage(ChatMessageBean messageBean) {
        messageBean.setRevoked(true);
        updateMessage(messageBean, REVOKE_PAYLOAD);
    }

这个方法里面的实现可以替换成ChatMessageAdapter.removeMessage就实现了消息的移除
