### ISSUE TITLE
单聊和群聊偶尔会漏消息

### ISSUE THREAD

**Issue by hhh88711** [netease-kit/nim-uikit-android#79]
# 单聊和群聊偶尔会漏消息
> 我暂时无法复现出,没办法把日志拿出来分析。能否进入单聊或者群聊,拉取下聊天记录?(要如何实现)

@shine2008

**Comment by shine2008** [comment]
https://faq.yunxin.163.com/kb/main/#/item/KB0179  可以通过上面的方法拉到我们的日志，里面会对打印聊天记录数据的数量，你可以看一下，是SDK的问题还是其他问题
