### ISSUE TITLE
uikit初始化，debug模式报错

### ISSUE THREAD

**Issue by xybCoder** [netease-kit/nim-uikit-android#82]
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/netease/nimlib/i/j;

**Comment by xybCoder** [comment]
V9.6.3版本，代码jar包引入

**Comment by xybCoder** [comment]
代码确实没有com/netease/nimlib/i/j;

**Comment by shine2008** [comment]
9.2.11版本 IM SDK 已经升级到9.6.4
